server:
  port: 9003

spring:
  main:
    # 如果有两个重复的bean被加载到容器内，允许第二个覆盖第一个，默认false
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/cas?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 2000
    host: 127.0.0.1
    port: 6379
    database: 0
mybatis:
  #配置mapper xml文件所在的路径
  mapper-locations: classpath:com.cas.dao/*.xml
  #Mybais 扫描别名包， 和注解@Alias联用
  type-aliases-package: com.cas.bean
  configuration:
    map-underscore-to-camel-case: true
    # 三种执行模式，simple,reuse,batch
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
